# Hermes WebUI — Docker setup for Windows + host Ollama
# Usage: pwsh -File scripts/docker-setup-windows.ps1

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$HermesHome = if ($env:HERMES_HOME) { $env:HERMES_HOME } else { Join-Path $env:USERPROFILE ".hermes" }
$Workspace = Join-Path $env:USERPROFILE "workspace"
$AgentDir = Join-Path $HermesHome "hermes-agent"

Write-Host "== Hermes WebUI Docker setup (Windows + Ollama) =="

foreach ($dir in @($HermesHome, $Workspace)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "Created $dir"
    }
}

if (-not (Test-Path $AgentDir)) {
    Write-Host "Cloning hermes-agent into $AgentDir ..."
    git clone --depth 1 https://github.com/NousResearch/hermes-agent.git $AgentDir
} else {
    Write-Host "hermes-agent already present: $AgentDir"
}

$hermesHomeDocker = ($HermesHome -replace '\\', '/')
$workspaceDocker = ($Workspace -replace '\\', '/')

$envContent = @"
# Generated by scripts/docker-setup-windows.ps1
UID=1000
GID=1000
HERMES_HOME=$hermesHomeDocker
HERMES_WORKSPACE=$workspaceDocker
HERMES_SKIP_CHMOD=1
OLLAMA_BASE_URL=http://host.docker.internal:11434/v1
HERMES_WEBUI_DEFAULT_LANGUAGE=ja
"@

Set-Content -Path (Join-Path $RepoRoot ".env") -Value $envContent -Encoding utf8NoBOM
Write-Host "Wrote .env"

Write-Host "Building and starting container (first build may take several minutes)..."
docker compose up -d --build

Write-Host ""
Write-Host "Waiting for /health ..."
$ok = $false
for ($i = 0; $i -lt 60; $i++) {
    try {
        $r = Invoke-WebRequest -Uri "http://127.0.0.1:8787/health" -UseBasicParsing -TimeoutSec 3
        if ($r.StatusCode -eq 200) { $ok = $true; break }
    } catch {}
    Start-Sleep -Seconds 2
}

if ($ok) {
    Write-Host "Hermes WebUI is up: http://127.0.0.1:8787"
} else {
    Write-Host "Server not healthy yet. Check: docker compose logs -f"
}

Write-Host ""
Write-Host "Ollama (first-run onboarding):"
Write-Host "  Base URL : http://host.docker.internal:11434/v1"
Write-Host "  Model    : pick from 'ollama list' (e.g. gemma3:27b-it-qat)"
Write-Host "  API key  : leave blank (local Ollama is keyless)"
Write-Host ""
Write-Host "Probe from container:"
Write-Host "  docker compose exec hermes-webui curl -sS http://host.docker.internal:11434/v1/models | head"
